//to create a new author
###
post http://localhost:4000/author-api/author
Content-Type: application/json

{
    "userType":"author1",
    "username":"testauthor1",
    "password":"testauthor1",
    "email":"testauthor1@gmail.com"
}

//to login
###
post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "userType":"author1",
    "username":"testauthor1",
    "password":"testauthor1"
}

//to create a new article
###
post http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
    "title":"Fundamental of Javascript",
    "category":"programming",
    "content":"JavaScript is a versatile programming language used primarily for web development. It enables dynamic content, interacts with HTML/CSS, handles events, and manipulates the DOM. Core concepts include variables, data types, functions, loops, conditionals, and objects. It supports asynchronous programming with callbacks, promises, and async/await.",
    "dateOfCreation":"{{$datetime iso8601}}",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"jashwanth",
    "comments": [],
    "status":true
}

//to update an article
###
put http://localhost:4000/author-api/article
Content-Type: application/json

{
    "articleId":"1716908271",
    "title":"Fundamental of Javascript",
    "category":"programming",
    "content":"JavaScript is a versatile programming language.",
    "dateOfCreation":"2024-05-28T14:57:51.973Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"jashwanth",
    "comments": [],
    "status":true

}

//to delete an article
###
put http://localhost:4000/author-api/article/1716908271
Content-Type: application/json

{
    "articleId":"1716908271",
    "title":"Fundamental of Javascript",
    "category":"programming",
    "content":"JavaScript is a versatile programming language.",
    "dateOfCreation":"2024-05-28T14:57:51.973Z",
    "dateOfModification":"{{$datetime iso8601}}",
    "username":"jashwanth",
    "comments": [],
    "status":true

}

//to read articles of an author
###
get http://localhost:4000/author-api/article/jashwanth


